[build]
    command = "vite build"
    functions = "netlify/functions"
    publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
    from = '/api/*'
    to = 'https://api.mpei.space/:splat'
    status = 200
    force = true
    headers = {AuthToken = "VITE_AUTH_TOKEN"}

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
